enum ServiceTypeEnum {
  MATERIA_SEMESTRE = 'MATERIA_SEMESTRE',
  ESTUDIANTE_SEMESTRE = 'ESTUDIANTE_SEMESTRE',
  ESTUDIANTE_SEMESTRE_MATERIA = 'ESTUDIANTE_SEMESTRE_MATERIA',
  ESTUDIANTE_SEMESTRE_MATERIA_PARALELO = 'ESTUDIANTE_SEMESTRE_MATERIA_PARALELO',
}

export default ServiceTypeEnum;
