export const CURSO_COMPLETO_ESTADO = {
  VALIDACION_CURSO: 'VALIDACIÓN CURSO',
  CONVOCAORIA: 'CONVOCATORIA',
  INSCRIPCION: 'INSCRIPCIÓN',
  VALIDACION_REQUISITOS: 'VALIDACIÓN REQUISITOS',
  VALIDACION_PRUEBAS: 'VALIDACIÓN PRUEBAS',
  CURSO: 'CURSO',
  REGISTRO_NOTAS: 'REGISTRO DE NOTAS',
  CIERRE: 'CIERRE CURSO',
  ABIERTOS: 'ABIERTOS',
}


