export const CURSO_COMPLETO_ESTADO = {
  VALIDACION_CURSO: 'VALIDACIÓN CURSO',
  CONVOCAORIA: 'CONVOCATORIA',
  INSCRIPCION: 'INSCRIPCIÓN',
  VALIDACION_REQUISITOS: 'VALIDACIÓN REQUISITOS',
  VALIDACION_PRUEBAS: 'VALIDACIÓN PRUEBAS',
  CURSO: 'CURSO',
  REGISTRO_NOTAS: 'REGISTRO DE NOTAS',
  CIERRE: 'CIERRE',
  CIERRE_PROCESO: 'CIERRE PROCESO',
  CIERRE_PRUEBAS: 'CIERRE PRUEBAS',
  CIERRE_VALIDACION: 'CIERRE VALIDACIÓN',
  CIERRE_INSCRITOS: 'CIERRE INSCRITOS',
  ABIERTOS: 'ABIERTOS',
  TODOS: 'TODOS',
  TODOS_CERRADOS: 'CERRADOS',
  MENU_CURSO: '/principal/especializacion/curso',
}


