export const PROFESIONALIZACION = {
  VALIDACION_CURSO: 'VALIDACIÓN CURSO',
  CONVOCATORIA: 'CONVOCATORIA',
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
  INSCRIPCION: 'INSCRIPCIÓN',
  VALIDACION_REQUISITOS: 'VALIDACIÓN REQUISITOS',
  REGISTRO_NOTAS: 'REGISTRO DE NOTAS',
  CIERRE: 'CIERRE',
  CIERRE_PROCESO: 'CIERRE PROCESO',
  CIERRE_PRUEBAS: 'CIERRE PRUEBAS',
  CIERRE_VALIDACION: 'CIERRE VALIDACIÓN',
  CIERRE_INSCRITOS: 'CIERRE INSCRITOS',
  ABIERTOS: 'ABIERTOS',
  MENU_CURSO: '/principal/especializacion/menu-gestion',
  INICIO: 'INICIO',
  SIN_PERIODO: 'SIN PERIODO',
  TODOS: 'TODOS',
  TODOS_CERRADOS: 'CERRADOS',
}


