const PROVINCIAS = [
  {nombre: 'Azuay'                          , id: 1},
  {nombre: 'Bolívar'                        , id: 2},
  {nombre: 'Cañar'                          , id: 3},
  {nombre: 'Carchi'                         , id: 4},
  {nombre: 'Chimborazo'                     , id: 5},
  {nombre: 'Cotopaxi'                       , id: 6},
  {nombre: 'El Oro'                         , id: 7},
  {nombre: 'Esmeraldas'                     , id: 8},
  {nombre: 'Galápagos'                      , id: 9},
  {nombre: 'Guayas'                         , id: 10},
  {nombre: 'Imbabura'                       , id: 11},
  {nombre: 'Loja'                           , id: 12},
  {nombre: 'Los Ríos'                       , id: 13},
  {nombre: 'Manabí'                         , id: 14},
  {nombre: 'Morona Santiago'                , id: 15},
  {nombre: 'Napo'                           , id: 16},
  {nombre: 'Orellana'                       , id: 17},
  {nombre: 'Pastaza'                        , id: 18},
  {nombre: 'Pichincha'                      , id: 19},
  {nombre: 'Santa Elena'                    , id: 20},
  {nombre: 'Santo Domingo de los Tsáchilas' , id: 21},
  {nombre: 'Sucumbíos'                      , id: 22},
  {nombre: 'Tungurahua'                     , id: 23},
  {nombre: 'Zamora Chinchipe'               , id: 24}
];


type CantonPorProvincia = {
  [key: string]: string[]
}

const CANTONES_POR_PROVINCIA: CantonPorProvincia = {
  'Azuay': [
    'Cuenca',
    'Gualaceo',
    'Paute',
    'Sigsig',
    'Girón',
    'San Fernando',
    'Santa Isabel',
    'Pucará',
    'Nabón',
  ],
  'Bolívar': [
    'Guaranda',
    'Chillanes',
    'Chimbo',
    'Echeandía',
    'San Miguel',
    'Caluma',
    'La Asunción',
    'La Magdalena',
  ],
  'Cañar': [
    'Azogues',
    'Biblián',
    'Cañar',
    'La Troncal',
  ],
  'Galápagos': [
    'Puerto Baquerizo Moreno',
    'Puerto Villamil',
    'Puerto Ayora',
  ],
  'Carchi': [
    'Mira',
    'Bolivar',
    'Tulcán',
    'El Ángel',
    'Huaca',
    'Julio Andrade',
    'La Paz',
    'San Gabriel',
  ],
  'Chimborazo': [
    'Riobamba',
    'Guano',
    'Chambo',
    'Colta',
    'Penipe',
    'Guamote',
    'Pallatanga',
    'Alausí',
    'Cunchi',
    'Cumandá',
    'Cajabamba',
    'Huigra',
    'San Andrés',
    'San Juan',
  ],
  'Cotopaxi': [
    'Latacunga',
    'Saquisilí',
    'Pujilí',
    'Salcedo',
    'Sigchos',
    'La Maná',
    'Chantillin',
    'El Corazón',
    'Guytacama',
    'Lasso',
    'Pastocalle',
    'Poaló',
    'Tanicuchi',
    'Toacazo',
    'Mulaló',
  ],
  'El Oro': [
    'El Guabo',
    'Huaquillas',
    'Machala',
    'Pasaje',
    'Piñas',
    'Puerto Bolivar',
    'Santa Rosa',
    'Zaruma',
    'Portovelo',
    'Arenillas',
    'Atahualpa',
    'Balsas',
    'Chilla',
    'Marcabeli',
  ],
  'Esmeraldas': [
    'Atacames',
    'Eloy Alfaro',
    'Esmeraldas',
    'Muisne',
  ],
  'Guayas': [
    'Guayaquil',
    'Durán',
    'Milagro',
    'Naranjal',
    'Salitre',
    'Samborondón',
  ],
  'Santa Elena': [
    'Santa Elena',
    'La Libertad',
    'Salinas',
    'La Concordia',
  ],
  'Loja': [
    'Loja',
    'Calvas',
    'Catamayo',
    'Celica',
    'Chaguarpamba',
  ],
  'Morona Santiago': [
    'Macas',
    'Gualaquiza',
    'Limon Indanza',
    'Santiago',
    'Sucúa',
  ],
  'Imbabura': [
    'Ibarra',
    'Antonio Ante',
    'Cotacachi',
    'Otavalo',
    'Pimampiro',
  ],
  'Los Ríos': [
    'Babahoyo',
    'Baba',
    'Montalvo',
    'Puebloviejo',
    'Quevedo',
  ],
  'Manabí': [
    'Portoviejo',
    'Bolívar',
    'Chone',
    'Jipijapa',
    'Junín',
  ],
  'Napo': [
    'Tena',
    'Archidona',
    'El Chaco',
    'Quijos',
  ],
  'Orellana': [
    'Orellana',
    'Aguarico',
    'La Joya de los Sachas',
    'Loreto',
  ],
  'Pastaza': [
    'Puyo',
    'Arajuno',
    'Cuyabeno',
  ],
  'Santo Domingo de los Tsáchilas': [
    'Santo Domingo',
    'Santo Domingo de los Colorados',
  ],
  'Pichincha': [
    'Quito',
    'Cayambe',
    'Machachi',
    'Pedro Moncayo',
    'Rumiñahui',
  ],
  'Sucumbíos': [
    'Nueva Loja',
    'Lago Agrio',
    'Puerto Francisco de Orellana',
  ],
  'Tungurahua': [
    'Ambato',
    'Baños de Agua Santa',
    'Cevallos',
    'Izamba',
    'Mocha',
  ],
  'Zamora Chinchipe': [
    'Zamora',
    'Chinchipe',
    'Nangaritza',
    'Yacuambi',
    'Yantzaza',
  ],
}

export {PROVINCIAS, CANTONES_POR_PROVINCIA};
