export const SERVICIOS_PUBLICOS_URLS: string[] = 
['/usuario/login', 
'/usuario/registro', 
'/usuario/resetPassword', 
'/usuario/guardarArchivo',
'/usuario/maxArchivo',
'/link',
'/provincia',
'/canton',
'/inscripcionfor/crear',
'/inscripcionfor/generaPin',
'/inscripcionfor/validaPin',
'/inscripcionfor/reenviaPin',
'/inscripcionfor/validafechas',
'/inscripcionfor/validaEdad',
'/periodoacademico/validaestado',
'/inscripcionfor/inscripcionPorCedula',
'/apicbdmq'
];
