export interface NotaEspecializacion {
  codEstudiante: number,
  codCursoEspecializacion: number,
  codNotaEspecializacion: number,
  codigoUnicoEstudiante: string,
  cedula: string,
  nombre: string,
  apellido: string,
  correoPersonal: string,
  correoInstitucional: string,
  notaFinalEspecializacion: number,
  notaSupletorio: number,
  codInscripcion: number,
  codInstructor: number,
}
